# Example GitHub Actions workflow for using PolyDup Action
# Copy this to .github/workflows/code-quality.yml in your repository

name: PolyDup Code Quality

on:
  pull_request:
    branches: [ main, master ]

jobs:
  duplicate-detection:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run PolyDup
        uses: wiesnerbernard/polydup-action@v0.1.0
        with:
          threshold: 50
          similarity: 0.85
          fail-on-duplicates: false
          comment-on-pr: true
